### PR TITLE
Add authentication and authorisation services

### PR DESCRIPTION
**Pull request by AlenDaGuy**

### CODE REVIEW

**Comment by KlintLee115** [comment]
@AlenDaGuy can u describe what this is for? idk the importance of this method

**Comment by AlenDaGuy** [comment]
> @AlenDaGuy can u describe what this is for? idk the importance of this method

Authorize attribute cant allow OR basis for roles checking so i created a helper function. its to help a custom authorize attribute for multiple roles checking using OR basis, which is what we are using now

**Comment by KlintLee115** [comment]
> > @AlenDaGuy can u describe what this is for? idk the importance of this method
> 
> Authorize attribute cant allow OR basis for roles checking so i created a helper function. its to help a custom authorize attribute for multiple roles checking using OR basis, which is what we are using now

oh ok, sorry i overlooked that

**Comment by KlintLee115** [comment]
thanks btw @AlenDaGuy

**Pull request merged**
